horas_mensais = float(input('Horas mensais de trabalho: '))
ganho_por_hora = float(input('Valor por hora trabalhada: '))
salario_bruto = (horas_mensais * ganho_por_hora)
inss = (8/100) * (salario_bruto)
imposto_de_renda = (11/100) * (salario_bruto)
sindicato = (5/100) * (salario_bruto)
descontos = (inss + imposto_de_renda + sindicato)
salario_liquido = (salario_bruto - descontos)
print(f'Salário Bruto: R$ {salario_bruto}')
print(f'INSS: R$ {inss}')
print(f'IR: R$ {imposto_de_renda}')
print(f'Sindicato: R$ {sindicato}')
print(f'Salário Líquido: R$ {salario_liquido}')
